apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-projetodevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-projetodevops
  template:
    metadata:
      labels:
        app: mysql-projetodevops
    spec:
      containers:
        - name: mysql-projetodevops
          image: otaviopax/mysql-projetodevops
          ports:
            - containerPort: 8000