apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-projetodevops
spec:
    replicas: 3
    selector:
        matchLabels:
          app: mysql
    template:
        metadata:
        labels:
            app: mysql
        spec:
        containers:
        - name: mysql-projetodevops
          image: otaviopax/mysql-projetodevops
          ports:
            - containerPort: 8000
