apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-projetodevops
spec:
  selector:
  replicas: 3
      matchLabels:
      app: mysql
  template:
    metadata:
    labels:
      app: mysql
    spec:
    containers:
    - name: mysql-projetodevops
      image: mysql-projetodevops
      ports:
        - containerPort: 8000
