apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: mysql-projetodevops
  newName: otaviopax/mysql-projetodevops
  newTag: 7460888f236b2c9ab6db627a655ff74630f9065e
